if(NOT DEFINED STRESS_EXE OR NOT DEFINED REPORT_PATH)
  message(FATAL_ERROR "Missing stress report test paths")
endif()
execute_process(COMMAND "${STRESS_EXE}" --frames 3 --warmup 2 --cycles 2
  --sprites 32 --entities 16 --bodies 16 --tiles 64 --voices 2 --report "${REPORT_PATH}"
  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Stress run failed: ${errors}")
endif()
file(READ "${REPORT_PATH}" report)
function(expect expected)
  string(JSON value GET "${report}" ${ARGN})
  if(NOT "${value}" STREQUAL "${expected}")
    message(FATAL_ERROR "${ARGN}: expected ${expected}, got ${value}")
  endif()
endfunction()
expect(feature_lab_stress_v1 schema)
expect(cpu mode)
expect(ON complete)
expect(ON resources_stable)
expect(2 run completed_cycles)
expect(6 run measured_frames)
expect(6 milliseconds simulation samples)
expect(6 milliseconds mixer samples)
expect(6 milliseconds frame samples)
expect(2 milliseconds load samples)
expect(0 milliseconds render_submit samples)
expect(0 milliseconds gpu_render samples)
expect(0 memory peak_targets)
expect(0 memory peak_uploaded_texture_bytes)
execute_process(COMMAND "${STRESS_EXE}" --frames 0 --report "${REPORT_PATH}"
  RESULT_VARIABLE rejected OUTPUT_QUIET ERROR_QUIET)
if(rejected EQUAL 0)
  message(FATAL_ERROR "Invalid run was accepted")
endif()
file(READ "${REPORT_PATH}" after)
if(NOT "${report}" STREQUAL "${after}")
  message(FATAL_ERROR "Invalid run replaced a valid report")
endif()
