cmake_minimum_required(VERSION 3.21)
include("${CMAKE_CURRENT_LIST_DIR}/../cmake/PackageSupport.cmake")
if(NOT DEFINED WORK_ROOT)
  message(FATAL_ERROR "WORK_ROOT is required")
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef id)
set(work "${WORK_ROOT}/manifest-${id}")
set(root "${work}/prefix with spaces")
file(MAKE_DIRECTORY "${root}/data")
file(WRITE "${root}/data/sample.bin" "abc\n")
package_manifest("${root}")
file(READ "${root}/FILES.sha256" original)
function(expect_rejection description)
  execute_process(COMMAND "${CMAKE_COMMAND}" -DMODE=verify "-DROOT=${root}"
    -P "${CMAKE_CURRENT_LIST_DIR}/../cmake/PackageSmoke.cmake"
    RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE error)
  if(result EQUAL 0)
    message(FATAL_ERROR "Accepted invalid manifest: ${description}")
  endif()
endfunction()
file(APPEND "${root}/data/sample.bin" "changed")
expect_rejection(corruption)
file(WRITE "${root}/data/sample.bin" "abc\n")
file(WRITE "${root}/FILES.sha256" "${original}${original}")
expect_rejection(duplicate)
file(WRITE "${root}/FILES.sha256" "not a checksum\n")
expect_rejection(malformed)
string(REPEAT "0" 64 zero_hash)
file(WRITE "${root}/FILES.sha256" "${zero_hash}  ../outside\n")
expect_rejection(traversal)
file(WRITE "${root}/FILES.sha256" "${zero_hash}  /absolute\n")
expect_rejection(absolute)
file(WRITE "${root}/FILES.sha256" "${original}")
file(RENAME "${root}/data/sample.bin" "${work}/backup")
expect_rejection(missing)
execute_process(COMMAND "${CMAKE_COMMAND}" -E create_symlink "${work}/backup" "${root}/data/sample.bin"
  RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Symlink fixture failed")
endif()
expect_rejection(symlink)
file(REMOVE "${root}/data/sample.bin")
file(RENAME "${work}/backup" "${root}/data/sample.bin")
file(WRITE "${root}/extra" "unlisted")
expect_rejection(unlisted)
file(REMOVE "${root}/extra")
package_verify("${root}")
# An outer checksum must match both the archive filename and the compressed bytes.
file(WRITE "${work}/example.tar.gz" "fixture")
file(SHA256 "${work}/example.tar.gz" hash)
file(WRITE "${work}/example.tar.gz.sha256" "${hash}  example.tar.gz\n")
package_verify_archive("${work}/example.tar.gz")
file(APPEND "${work}/example.tar.gz" "corrupt")
execute_process(COMMAND "${CMAKE_COMMAND}" "-DARCHIVE=${work}/example.tar.gz" "-DWORK_ROOT=${work}/unused"
  -DMODE=headless -P "${CMAKE_CURRENT_LIST_DIR}/../cmake/PackageSmoke.cmake"
  RESULT_VARIABLE result ERROR_VARIABLE error OUTPUT_QUIET)
if(result EQUAL 0 OR NOT error MATCHES "Archive checksum mismatch")
  message(FATAL_ERROR "Bad compressed archive checksum was not rejected before extraction")
endif()
file(REMOVE_RECURSE "${work}")
message(STATUS "Package manifest and archive integrity cases passed")
