# Shared by the packager and tests. All paths are explicit; no shell commands.
function(package_verify root)
  if(NOT EXISTS "${root}/FILES.sha256")
    message(FATAL_ERROR "Package manifest is missing")
  endif()
  file(REAL_PATH "${root}" canonical_root)
  file(STRINGS "${root}/FILES.sha256" records)
  set(expected)
  foreach(record IN LISTS records)
    if(NOT record MATCHES "^([0-9a-f]+)  ([A-Za-z0-9_./-]+)$")
      message(FATAL_ERROR "Invalid package manifest record")
    endif()
    set(hash "${CMAKE_MATCH_1}")
    set(relative "${CMAKE_MATCH_2}")
    string(LENGTH "${hash}" hash_length)
    if(NOT hash_length EQUAL 64 OR relative MATCHES "(^/|(^|/)\\.\\.?(/|$)|//)" OR relative STREQUAL "FILES.sha256")
      message(FATAL_ERROR "Invalid package manifest path/hash")
    endif()
    if(relative IN_LIST expected OR NOT EXISTS "${root}/${relative}" OR IS_DIRECTORY "${root}/${relative}" OR IS_SYMLINK "${root}/${relative}")
      message(FATAL_ERROR "Missing, duplicate or non-regular package file: ${relative}")
    endif()
    file(REAL_PATH "${root}/${relative}" resolved)
    file(RELATIVE_PATH contained "${canonical_root}" "${resolved}")
    if(contained MATCHES "^\\.\\./" OR IS_ABSOLUTE "${contained}")
      message(FATAL_ERROR "Package path escapes its root")
    endif()
    file(SHA256 "${root}/${relative}" actual_hash)
    if(NOT hash STREQUAL actual_hash)
      message(FATAL_ERROR "Package checksum mismatch: ${relative}")
    endif()
    list(APPEND expected "${relative}")
  endforeach()
  file(GLOB_RECURSE actual LIST_DIRECTORIES FALSE RELATIVE "${root}" "${root}/*")
  list(REMOVE_ITEM actual "FILES.sha256")
  list(SORT expected)
  list(SORT actual)
  if(NOT expected OR NOT "${expected}" STREQUAL "${actual}")
    message(FATAL_ERROR "Package has unlisted or missing files")
  endif()
endfunction()

function(package_manifest root)
  file(GLOB_RECURSE files LIST_DIRECTORIES FALSE RELATIVE "${root}" "${root}/*")
  list(SORT files)
  set(text "")
  foreach(relative IN LISTS files)
    if(relative STREQUAL "FILES.sha256")
      continue()
    endif()
    if(NOT relative MATCHES "^[A-Za-z0-9_./-]+$" OR IS_SYMLINK "${root}/${relative}")
      message(FATAL_ERROR "Unsupported package path: ${relative}")
    endif()
    file(SHA256 "${root}/${relative}" hash)
    string(APPEND text "${hash}  ${relative}\n")
  endforeach()
  file(WRITE "${root}/FILES.sha256" "${text}")
  package_verify("${root}")
endfunction()

function(package_extract archive directory out_root)
  file(MAKE_DIRECTORY "${directory}")
  execute_process(COMMAND "${CMAKE_COMMAND}" -E tar xfz "${archive}"
    WORKING_DIRECTORY "${directory}" RESULT_VARIABLE result ERROR_VARIABLE error)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Cannot extract package: ${error}")
  endif()
  file(GLOB roots "${directory}/*")
  list(LENGTH roots count)
  if(NOT count EQUAL 1 OR NOT IS_DIRECTORY "${roots}")
    message(FATAL_ERROR "Expected one package root")
  endif()
  package_verify("${roots}")
  set(${out_root} "${roots}" PARENT_SCOPE)
endfunction()

function(package_headless root work)
  file(MAKE_DIRECTORY "${work}/unrelated cwd/assets")
  file(WRITE "${work}/unrelated cwd/assets/facility.scene" "Not a facility; CWD must not be used.\n")
  set(environment "${CMAKE_COMMAND}" -E env --unset=DISPLAY --unset=LD_LIBRARY_PATH --unset=LD_PRELOAD)
  execute_process(COMMAND ${environment} "${root}/bin/feature_lab" --verify
    WORKING_DIRECTORY "${work}/unrelated cwd" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  file(WRITE "${work}/game-verify.log" "${output}${error}")
  if(NOT result EQUAL 0 OR NOT output MATCHES "\"passed\":true")
    message(FATAL_ERROR "Relocated gameplay verification failed: ${output}${error}")
  endif()
  set(arguments --frames 4 --warmup 2 --cycles 2 --sprites 32 --tiles 64 --entities 16 --bodies 16 --voices 2)
  foreach(program IN ITEMS stress_bench feature_lab)
    set(mode)
    if(program STREQUAL "feature_lab")
      set(mode --stress --cpu-only)
    endif()
    execute_process(COMMAND ${environment} "${root}/bin/${program}" ${mode} ${arguments} --report "${work}/${program}.json"
      WORKING_DIRECTORY "${work}/unrelated cwd" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
      message(FATAL_ERROR "Relocated ${program} failed: ${output}${error}")
    endif()
    file(READ "${work}/${program}.json" report)
    string(JSON complete GET "${report}" complete)
    string(JSON stable GET "${report}" resources_stable)
    string(JSON measured GET "${report}" run measured_frames)
    string(JSON checksum GET "${report}" run checksum)
    if(NOT complete OR NOT stable OR NOT measured EQUAL 8)
      message(FATAL_ERROR "Invalid relocated stress result")
    endif()
    if(DEFINED previous_checksum AND NOT previous_checksum STREQUAL checksum)
      message(FATAL_ERROR "Relocated CPU entry points diverged")
    endif()
    set(previous_checksum "${checksum}")
  endforeach()
  execute_process(COMMAND "${CMAKE_COMMAND}" -E create_symlink "${root}/bin/feature_lab" "${work}/game-link"
    RESULT_VARIABLE result)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Cannot create relocation-test symlink")
  endif()
  execute_process(COMMAND ${environment} "${work}/game-link" --verify
    WORKING_DIRECTORY "${work}/unrelated cwd" RESULT_VARIABLE result ERROR_VARIABLE error OUTPUT_QUIET)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Symlinked package launch failed: ${error}")
  endif()
  # Modify only the extracted test copy, never the archive or source assets.
  file(RENAME "${root}/share/feature_lab" "${root}/share/hidden-assets")
  execute_process(COMMAND ${environment} "${root}/bin/feature_lab" --verify
    WORKING_DIRECTORY "${work}/unrelated cwd" RESULT_VARIABLE missing_result ERROR_VARIABLE missing_error OUTPUT_QUIET)
  execute_process(COMMAND ${environment} "${root}/bin/feature_lab" --verify --assets "${root}/share/hidden-assets"
    WORKING_DIRECTORY "${work}/unrelated cwd" RESULT_VARIABLE override_result ERROR_VARIABLE override_error OUTPUT_QUIET)
  file(RENAME "${root}/share/hidden-assets" "${root}/share/feature_lab")
  if(missing_result EQUAL 0 OR NOT missing_error MATCHES "Cannot find assets" OR NOT override_result EQUAL 0)
    message(FATAL_ERROR "Asset-root isolation/override failed: ${missing_error}${override_error}")
  endif()
  package_verify("${root}")
endfunction()

function(package_verify_archive archive)
  if(NOT EXISTS "${archive}.sha256")
    message(FATAL_ERROR "Archive checksum file is missing")
  endif()
  file(STRINGS "${archive}.sha256" records)
  list(LENGTH records count)
  if(NOT count EQUAL 1 OR NOT records MATCHES "^([0-9a-f]+)  ([A-Za-z0-9_.-]+)$")
    message(FATAL_ERROR "Invalid archive checksum record")
  endif()
  set(expected "${CMAKE_MATCH_1}")
  set(recorded_name "${CMAKE_MATCH_2}")
  get_filename_component(name "${archive}" NAME)
  file(SHA256 "${archive}" actual)
  if(NOT recorded_name STREQUAL name OR NOT expected STREQUAL actual)
    message(FATAL_ERROR "Archive checksum mismatch")
  endif()
endfunction()
