cmake_minimum_required(VERSION 3.21)
include("${CMAKE_CURRENT_LIST_DIR}/PackageSupport.cmake")
if(MODE STREQUAL "verify")
  package_verify("${ROOT}")
  return()
endif()
if(NOT DEFINED ARCHIVE OR NOT DEFINED WORK_ROOT)
  message(FATAL_ERROR "ARCHIVE and WORK_ROOT are required")
endif()
if(MODE STREQUAL "graphics" AND "$ENV{DISPLAY}" STREQUAL "")
  message("SKIP: package graphics smoke requires DISPLAY")
  return()
endif()
package_verify_archive("${ARCHIVE}")
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef id)
set(work "${WORK_ROOT}/smoke-${id}")
package_extract("${ARCHIVE}" "${work}/unpack" extracted)
set(root "${work}/relocated package with spaces")
file(RENAME "${extracted}" "${root}")
if(MODE STREQUAL "graphics")
  file(MAKE_DIRECTORY "${work}/cwd/assets")
  file(WRITE "${work}/cwd/assets/facility.scene" "CWD must not be used\n")
  execute_process(COMMAND "${CMAKE_COMMAND}" -E env --unset=LD_LIBRARY_PATH --unset=LD_PRELOAD
    "${root}/bin/feature_lab" --scripted --frames 1600 --no-audio --no-vsync
    --user-data "${work}/user" --record-replay "${work}/run.erpl" --save-slot 1 --screenshot "${work}/game.ppm"
    WORKING_DIRECTORY "${work}/cwd" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 90)
  file(WRITE "${work}/game.log" "${output}${error}")
  if(NOT result EQUAL 0 OR NOT output MATCHES "door_completions=1 collected=3"
    OR NOT EXISTS "${work}/game.ppm" OR NOT EXISTS "${work}/user/state/slot-1.esav")
    message(FATAL_ERROR "Packaged OpenGL gameplay failed (${work}): ${output}${error}")
  endif()
  execute_process(COMMAND "${CMAKE_COMMAND}" -E env --unset=DISPLAY --unset=LD_LIBRARY_PATH --unset=LD_PRELOAD
    "${root}/bin/feature_lab" --verify-replay "${work}/run.erpl"
    WORKING_DIRECTORY "${work}/cwd" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT result EQUAL 0 OR NOT output MATCHES "verified commands=1600 ticks=1381")
    message(FATAL_ERROR "Packaged replay verification failed: ${output}${error}")
  endif()
  execute_process(COMMAND "${CMAKE_COMMAND}" -E env --unset=LD_LIBRARY_PATH --unset=LD_PRELOAD
    "${root}/bin/feature_lab" --stress --frames 4 --warmup 2 --cycles 2
    --sprites 8192 --report "${work}/stress.json" --screenshot "${work}/stress.ppm"
    WORKING_DIRECTORY "${work}/cwd" RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE error TIMEOUT 30)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Packaged OpenGL stress failed: ${error}")
  endif()
  file(READ "${work}/stress.json" report)
  string(JSON stable GET "${report}" resources_stable)
  string(JSON complete GET "${report}" complete)
  string(JSON measured GET "${report}" run measured_frames)
  if(NOT stable OR NOT complete OR NOT measured EQUAL 8 OR NOT EXISTS "${work}/stress.ppm")
    message(FATAL_ERROR "Packaged stress resources/completion check failed")
  endif()
else()
  package_headless("${root}" "${work}/checks")
  # A checksum mismatch must fail before trusting packaged payloads.
  set(texture "${root}/share/feature_lab/textures/checker.etex")
  configure_file("${texture}" "${work}/texture-backup" COPYONLY)
  file(APPEND "${texture}" "corrupt")
  execute_process(COMMAND "${CMAKE_COMMAND}" -DMODE=verify "-DROOT=${root}" -P "${CMAKE_CURRENT_LIST_FILE}"
    RESULT_VARIABLE rejected OUTPUT_QUIET ERROR_VARIABLE error)
  configure_file("${work}/texture-backup" "${texture}" COPYONLY)
  if(rejected EQUAL 0 OR NOT error MATCHES "checksum mismatch")
    message(FATAL_ERROR "Corrupted package payload was not rejected")
  endif()
  file(WRITE "${root}/unlisted.txt" "unexpected")
  execute_process(COMMAND "${CMAKE_COMMAND}" -DMODE=verify "-DROOT=${root}" -P "${CMAKE_CURRENT_LIST_FILE}"
    RESULT_VARIABLE rejected OUTPUT_QUIET ERROR_VARIABLE error)
  file(REMOVE "${root}/unlisted.txt")
  if(rejected EQUAL 0 OR NOT error MATCHES "unlisted")
    message(FATAL_ERROR "Unlisted package payload was not rejected")
  endif()
endif()
package_verify("${root}")
message(STATUS "Package ${MODE} smoke passed; evidence: ${work}")
